version: '3.4'

networks: 
  dev:
    driver: bridge

services:
  demo-app:
    image: docker.io/library/patientdemo      
    container_name: hospitalapp-services
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HospitalApiConnectionString=User Id=postgres;Password=slayervsdrow;Host=app_db;Port=5432;Database=hospital_api;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
      - JWT_SECRET=DhftOS5uphK3vmCJQrexST1RsyjZBjXWRgJMFPU4
      - ALGORITHM=HmacSha256
    depends_on:
      - app_db
    networks:
      - dev
  
  app_db:
    image: postgres:latest
    container_name: hospital_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=slayervsdrow
      - POSTGRES_DB=hospital_api
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=HIDT@domain.com
      - PGADMIN_DEFAULT_PASSWORD=MySecret
    ports:
      - "5050:80"
    depends_on:
      - app_db
    networks:
      - dev
volumes:
  app_data:
